<a href="https://colab.research.google.com/github/daniyalcr9/SDandA/blob/main/20sw107_lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#task1
import numpy as np

# Using np.arange to generate an array of even numbers from 2 to 32 (inclusive)
even_numbers = np.arange(2, 33, 2)

# Reshape the even_numbers array into a 4x4 ndarray
X = even_numbers.reshape(4,4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
#task 2
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print("Original Array X:")
print(X)
print("\nArray Y with Odd Numbers:")
print(Y)


Original Array X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [3]:
#task3
import numpy as np

# Use Broadcasting to create the desired ndarray
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
